
---
title: "Adult Census"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: image1.png
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
df <- read.csv('https://bryantstats.github.io/math421/data/adult_census.csv')
adultcensus_sex <- unique(df$sex)
```

{.sidebar}
=======================================================================

This data set includes 15 variables with 32,561 observations. Variables include but are not limited to sex, marital status, race and income. 

```{r}
library(shiny)
library(packrat)
library(rsconnect)
checkboxGroupInput(inputId = "MS_input", 
                   label = h3("Marital Status"),
                   choices = unique(df$marital.status), 
                   inline = TRUE,
                   selected = 'Widowed')

```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot

```{r}
renderPlotly({
  p6 <- df %>% 
    filter(marital.status %in% input$MS_input) %>% 
    ggplot(aes(x=age, color=race))+
    geom_density()
  ggplotly(p6)
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Bar Plot

```{r}
renderPlotly({
  p7 <- df %>% 
    filter(marital.status %in% input$MS_input) %>% 
    ggplot(aes(x=education, fill=race))+
    geom_bar()
  ggplotly(p7)})
```
