
---
title: "Adult Census"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: image1.png
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
library(shiny)
library(packrat)
library(rsconnect)
df <- read.csv('https://bryantstats.github.io/math421/data/adult_census.csv')

adultcensus_sex <- unique(df$sex)
```

{.sidebar}
=======================================================================

The sinking of the Titanic is one of the most infamous shipwrecks in history. While there was some element of luck involved in surviving, it seems some groups of people were more likely to survive than others.  Select the input for the plots. 

```{r}
selectInput(inputId = "sex_input",
            label = h3("Select Gender"),
            choice = adultcensus_sex,
            selected = 'Male')
```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot

```{r}
renderPlotly({
  p4 <- df %>% 
    filter(sex==input$sex_input) %>% 
    ggplot(aes(x=age, color=race))+
    geom_density()
  ggplotly(p4)
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Bar Plot

```{r}
renderPlotly({
  p5 <- df %>% 
    filter(sex==input$sex_input) %>% 
    ggplot(aes(x=race, fill=marital.status))+
    geom_bar()
  ggplotly(p5)
})
```
